import type { BusinessIdentifiers, Finding, Severity } from "../types";

export const SEVERITY_WEIGHTS: Record<Severity, number> = {
  critical: 60,
  high: 40,
  medium: 15,
  low: 5,
  info: 0,
};

export const FRAUD_THRESHOLD = 40;

export function finding(code: string, severity: Severity, title: string, detail: string): Finding {
  return { code, severity, title, detail };
}

const EDITING_SOFTWARE = [
  "photoshop",
  "lightroom",
  "illustrator",
  "indesign",
  "gimp",
  "canva",
  "pixlr",
  "snapseed",
  "picsart",
  "photopea",
  "affinity",
  "paint.net",
  "krita",
  "figma",
  "sketch",
  "fotor",
  "befunky",
  "photoscape",
  "polarr",
  "vsco",
  "facetune",
  "ilovepdf",
  "smallpdf",
  "sejda",
  "pdfescape",
  "pdffiller",
  "pdf-xchange",
  "pdfelement",
  "foxit",
  "nitro",
  "soda pdf",
  "pdfsam",
  "pdf24",
  "acrobat pro",
  "acrobat dc",
];

const OFFICE_SOFTWARE = [
  "microsoft word",
  "microsoft® word",
  "microsoft office",
  "libreoffice",
  "openoffice",
  "google docs",
  "wps office",
  "acrobat pdfmaker",
  "apple pages",
  "powerpoint",
  "excel",
];

function match(value: string | null | undefined, names: string[]): string | null {
  if (!value) return null;
  const lowered = value.toLowerCase();
  return names.some((name) => lowered.includes(name)) ? value.trim() : null;
}

export function editingSoftwareMatch(value: string | null | undefined): string | null {
  return match(value, EDITING_SOFTWARE);
}

export function softwareFindings(source: string, value: string | null | undefined): Finding[] {
  const edited = editingSoftwareMatch(value);
  if (edited) {
    return [
      finding(
        "editing_software",
        "high",
        "Edited with photo/document editing software",
        `The ${source} metadata records '${edited}'. Official documents and bank receipts are generated by the issuing system, not by editing tools.`,
      ),
    ];
  }
  const office = match(value, OFFICE_SOFTWARE);
  if (office) {
    return [
      finding(
        "office_software",
        "medium",
        "Produced by an office/word-processing application",
        `The ${source} metadata records '${office}'. Bank receipts, tax invoices and government certificates are generated by their issuing systems, not typed in an office app.`,
      ),
    ];
  }
  return [];
}

const EXIF_DATE = /^(\d{4})[:-](\d{2})[:-](\d{2})[ T](\d{2}):(\d{2}):(\d{2})/;
const PDF_DATE = /^D?:?(\d{4})(\d{2})?(\d{2})?(\d{2})?(\d{2})?(\d{2})?(?:([+\-Z])(\d{2})?'?(\d{2})?'?)?/;

function utcDate(y: number, mo: number, d: number, h = 0, mi = 0, s = 0): Date | null {
  if (mo < 1 || mo > 12 || d < 1 || d > 31 || h > 23 || mi > 59 || s > 60) return null;
  const date = new Date(Date.UTC(y, mo - 1, d, h, mi, s));
  return date.getUTCMonth() === mo - 1 && date.getUTCDate() === d ? date : null;
}

export function parseDatetime(value: string | null | undefined): Date | null {
  if (!value) return null;
  const trimmed = value.trim();
  let m = EXIF_DATE.exec(trimmed);
  if (m) {
    const [y, mo, d, h, mi, s] = m.slice(1).map(Number);
    return utcDate(y, mo, d, h, mi, s);
  }
  m = PDF_DATE.exec(trimmed);
  if (m) {
    const [, y, mo, d, h, mi, s, sign, oh, om] = m;
    const date = utcDate(Number(y), Number(mo ?? 1), Number(d ?? 1), Number(h ?? 0), Number(mi ?? 0), Number(s ?? 0));
    if (!date) return null;
    if ((sign === "+" || sign === "-") && oh) {
      const offsetMs = (Number(oh) * 60 + Number(om ?? 0)) * 60_000;
      return new Date(date.getTime() + (sign === "+" ? -offsetMs : offsetMs));
    }
    return date;
  }
  return null;
}

export function formatUtc(date: Date): string {
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${date.getUTCFullYear()}-${pad(date.getUTCMonth() + 1)}-${pad(date.getUTCDate())} ${pad(date.getUTCHours())}:${pad(date.getUTCMinutes())} UTC`;
}

function humanize(ms: number): string {
  const seconds = Math.floor(ms / 1000);
  if (seconds < 3600) return `${Math.floor(seconds / 60)} minutes`;
  if (seconds < 86400) return `${Math.floor(seconds / 3600)} hours`;
  return `${Math.floor(seconds / 86400)} days`;
}

const DAY_MS = 86_400_000;

export function checkDates(created: Date | null, modified: Date | null, now: Date = new Date()): Finding[] {
  const findings: Finding[] = [];
  if (created && modified) {
    const delta = modified.getTime() - created.getTime();
    if (delta > 2 * 60_000) {
      findings.push(
        finding(
          "modified_after_creation",
          "medium",
          "Document was modified after it was created",
          `Created ${formatUtc(created)} but last modified ${formatUtc(modified)} (${humanize(delta)} later). Genuine system-generated documents are normally not touched after issue.`,
        ),
      );
    } else if (delta < 0) {
      findings.push(
        finding(
          "modified_before_creation",
          "high",
          "Modification date is earlier than creation date",
          "The timestamps are inconsistent, which indicates the metadata was tampered with.",
        ),
      );
    }
  }
  for (const [label, dt] of [
    ["creation", created],
    ["modification", modified],
  ] as const) {
    if (dt && dt.getTime() > now.getTime() + DAY_MS) {
      findings.push(
        finding(
          `future_${label}_date`,
          "high",
          `The ${label} date is in the future`,
          `The file claims a ${label} time of ${formatUtc(dt)}, which has not happened yet.`,
        ),
      );
    }
  }
  return findings;
}

const EMIRATES_ID = /\b784[- ]?(\d{4})[- ]?(\d{7})[- ]?(\d)\b/g;
const IBAN = /\b([A-Z]{2}\d{2}(?: ?[A-Z0-9]{4}){2,7}(?: ?[A-Z0-9]{1,3})?)\b/g;
const TEXT_DATE = /\b(\d{1,2})[/\-.](\d{1,2})[/\-.](\d{4})\b/g;
const IBAN_COUNTRIES = ["AE", "SA", "QA", "BH", "KW", "OM", "GB", "DE", "FR"];

function luhnOk(digits: string): boolean {
  let total = 0;
  const reversed = digits.split("").reverse();
  for (let i = 0; i < reversed.length; i++) {
    let n = Number(reversed[i]);
    if (i % 2 === 1) {
      n *= 2;
      if (n > 9) n -= 9;
    }
    total += n;
  }
  return total % 10 === 0;
}

function ibanOk(iban: string): boolean {
  const rearranged = iban.slice(4) + iban.slice(0, 4);
  let remainder = 0;
  for (const ch of rearranged) {
    const digits = String(parseInt(ch, 36));
    for (const d of digits) remainder = (remainder * 10 + Number(d)) % 97;
  }
  return remainder === 1;
}

export function checkTextContent(text: string, now: Date = new Date()): Finding[] {
  const findings: Finding[] = [];
  if (!text) return findings;

  for (const m of text.matchAll(EMIRATES_ID)) {
    const digits = `784${m[1]}${m[2]}${m[3]}`;
    const year = Number(m[1]);
    if (!luhnOk(digits) || year < 1900 || year > now.getUTCFullYear()) {
      findings.push(
        finding(
          "invalid_emirates_id",
          "critical",
          "Emirates ID number fails validation",
          `The ID number ${m[0]} does not pass the official checksum. Real Emirates ID numbers always validate.`,
        ),
      );
    }
  }

  for (const m of text.toUpperCase().matchAll(IBAN)) {
    const iban = m[1].replace(/ /g, "");
    if (iban.length < 15 || !IBAN_COUNTRIES.includes(iban.slice(0, 2))) continue;
    if (iban.startsWith("AE") && iban.length !== 23) {
      findings.push(
        finding(
          "invalid_iban_length",
          "high",
          "IBAN has the wrong length",
          `UAE IBANs are 23 characters; '${iban}' has ${iban.length}.`,
        ),
      );
      continue;
    }
    if (!ibanOk(iban)) {
      findings.push(
        finding(
          "invalid_iban",
          "high",
          "IBAN fails checksum",
          `The account number '${iban}' is not a valid IBAN. Genuine bank receipts never contain an invalid IBAN.`,
        ),
      );
    }
  }

  for (const m of text.matchAll(TEXT_DATE)) {
    let d = Number(m[1]);
    let mo = Number(m[2]);
    const y = Number(m[3]);
    if (mo > 12 && d <= 12) [d, mo] = [mo, d];
    const dt = utcDate(y, mo, d);
    if (!dt) continue;
    if (dt.getTime() > now.getTime() + DAY_MS) {
      findings.push(
        finding(
          "future_date_in_text",
          "medium",
          "Document text contains a future date",
          `The document mentions ${m[0]}, which is after today.`,
        ),
      );
      break;
    }
  }

  return findings;
}

const LICENCE_NO =
  /(?:trade|commercial|business|economic|professional)?\s*licen[cs]e\s*(?:no|number|#|№)?\s*[:.-]?\s*([A-Z]{0,4}[-/ ]?\d{4,10}(?:[-/]\d{1,6})?)/gi;
const TRN = /\b(?:TRN|tax\s+registration\s+(?:no|number)|VAT\s+(?:no|number|reg))\.?\s*[:#-]?\s*(\d[\d ]{7,18}\d)/gi;
const TRADE_NAME = /(?:trade|company|business|establishment)\s+name\s*[:-]\s*([^\n]{3,80})/i;

export function emptyBusiness(): BusinessIdentifiers {
  return {
    licence_numbers: [],
    tax_registration_numbers: [],
    trade_name: null,
  };
}

export function extractBusinessIdentifiers(text: string): BusinessIdentifiers {
  const ids = emptyBusiness();
  if (!text) return ids;
  for (const m of text.matchAll(LICENCE_NO)) {
    const value = m[1].replace(/\s+/g, "").toUpperCase();
    if (!ids.licence_numbers.includes(value)) ids.licence_numbers.push(value);
  }
  for (const m of text.matchAll(TRN)) {
    const digits = m[1].replace(/\D/g, "");
    if (!ids.tax_registration_numbers.includes(digits)) ids.tax_registration_numbers.push(digits);
  }
  const m = TRADE_NAME.exec(text);
  if (m) ids.trade_name = m[1].trim().replace(/[.,;]+$/, "");
  return ids;
}

export function checkBusinessIdentifiers(ids: BusinessIdentifiers): Finding[] {
  return ids.tax_registration_numbers
    .filter((trn) => trn.length !== 15 || !trn.startsWith("100"))
    .map((trn) =>
      finding(
        "invalid_trn",
        "high",
        "Tax Registration Number has an invalid format",
        `The TRN '${trn}' is not a valid UAE Federal Tax Authority number. Genuine UAE tax invoices carry a 15-digit TRN starting with 100.`,
      ),
    );
}

export function latin1(bytes: Uint8Array, start = 0, end = bytes.length): string {
  let out = "";
  const CHUNK = 8192;
  for (let i = start; i < end; i += CHUNK) {
    out += String.fromCharCode.apply(null, Array.from(bytes.subarray(i, Math.min(i + CHUNK, end))));
  }
  return out;
}

export function utf8(bytes: Uint8Array): string {
  try {
    return decodeURIComponent(
      latin1(bytes)
        .split("")
        .map((c) => `%${c.charCodeAt(0).toString(16).padStart(2, "0")}`)
        .join(""),
    );
  } catch {
    return latin1(bytes);
  }
}

export function indexOfBytes(haystack: Uint8Array, needle: string, from = 0): number {
  const n = needle.length;
  const first = needle.charCodeAt(0);
  outer: for (let i = from; i <= haystack.length - n; i++) {
    if (haystack[i] !== first) continue;
    for (let j = 1; j < n; j++) if (haystack[i + j] !== needle.charCodeAt(j)) continue outer;
    return i;
  }
  return -1;
}

export function countBytes(haystack: Uint8Array, needle: string): number {
  let count = 0;
  let idx = indexOfBytes(haystack, needle);
  while (idx !== -1) {
    count++;
    idx = indexOfBytes(haystack, needle, idx + needle.length);
  }
  return count;
}

export function extractXmp(data: Uint8Array): string {
  const start = indexOfBytes(data, "<x:xmpmeta");
  if (start === -1) return "";
  const end = indexOfBytes(data, "</x:xmpmeta>", start);
  return end === -1 ? "" : utf8(data.subarray(start, end + 12));
}
