from __future__ import annotations

import re
from datetime import UTC, datetime, timedelta

from app.models import Finding, Severity

EDITING_SOFTWARE = (
    "photoshop",
    "lightroom",
    "illustrator",
    "indesign",
    "gimp",
    "canva",
    "pixlr",
    "snapseed",
    "picsart",
    "photopea",
    "affinity",
    "paint.net",
    "krita",
    "figma",
    "sketch",
    "fotor",
    "befunky",
    "photoscape",
    "polarr",
    "vsco",
    "facetune",
    "ilovepdf",
    "smallpdf",
    "sejda",
    "pdfescape",
    "pdffiller",
    "pdf-xchange",
    "pdfelement",
    "foxit",
    "nitro",
    "soda pdf",
    "pdfsam",
    "pdf24",
    "acrobat pro",
    "acrobat dc",
)

OFFICE_SOFTWARE = (
    "microsoft word",
    "microsoft® word",
    "microsoft office",
    "libreoffice",
    "openoffice",
    "google docs",
    "wps office",
    "acrobat pdfmaker",
    "apple pages",
    "powerpoint",
    "excel",
)


def _match(value: str | None, names: tuple[str, ...]) -> str | None:
    if not value:
        return None
    lowered = value.lower()
    for name in names:
        if name in lowered:
            return value.strip()
    return None


def editing_software_match(value: str | None) -> str | None:
    return _match(value, EDITING_SOFTWARE)


def office_software_match(value: str | None) -> str | None:
    return _match(value, OFFICE_SOFTWARE)


def software_findings(source: str, value: str | None) -> list[Finding]:
    edited = editing_software_match(value)
    if edited:
        return [
            Finding(
                code="editing_software",
                severity=Severity.HIGH,
                title="Edited with photo/document editing software",
                detail=(
                    f"The {source} metadata records '{edited}'. Official documents and bank "
                    "receipts are generated by the issuing system, not by editing tools."
                ),
            )
        ]
    office = office_software_match(value)
    if office:
        return [
            Finding(
                code="office_software",
                severity=Severity.MEDIUM,
                title="Produced by an office/word-processing application",
                detail=(
                    f"The {source} metadata records '{office}'. Bank receipts, tax invoices and "
                    "government certificates are generated by their issuing systems, not typed in an office app."
                ),
            )
        ]
    return []


_EXIF_DATE = re.compile(r"^(\d{4})[:\-](\d{2})[:\-](\d{2})[ T](\d{2}):(\d{2}):(\d{2})")
_PDF_DATE = re.compile(
    r"^D?:?(\d{4})(\d{2})?(\d{2})?(\d{2})?(\d{2})?(\d{2})?"
    r"(?:([+\-Z])(\d{2})?'?(\d{2})?'?)?"
)


def parse_datetime(value: str | None) -> datetime | None:
    if not value:
        return None
    value = value.strip()
    m = _EXIF_DATE.match(value)
    if m:
        try:
            return datetime(*(int(g) for g in m.groups()), tzinfo=UTC)
        except ValueError:
            return None
    m = _PDF_DATE.match(value)
    if m:
        y, mo, d, h, mi, s, sign, oh, om = m.groups()
        try:
            dt = datetime(
                int(y),
                int(mo or 1),
                int(d or 1),
                int(h or 0),
                int(mi or 0),
                int(s or 0),
                tzinfo=UTC,
            )
        except ValueError:
            return None
        if sign in ("+", "-") and oh:
            offset = timedelta(hours=int(oh), minutes=int(om or 0))
            dt = dt - offset if sign == "+" else dt + offset
        return dt
    return None


def check_dates(
    created: datetime | None,
    modified: datetime | None,
    *,
    now: datetime | None = None,
) -> list[Finding]:
    findings: list[Finding] = []
    now = now or datetime.now(UTC)
    if created and modified:
        delta = modified - created
        if delta > timedelta(minutes=2):
            findings.append(
                Finding(
                    code="modified_after_creation",
                    severity=Severity.MEDIUM,
                    title="Document was modified after it was created",
                    detail=(
                        f"Created {created:%Y-%m-%d %H:%M} UTC but last modified "
                        f"{modified:%Y-%m-%d %H:%M} UTC ({_humanize(delta)} later). "
                        "Genuine system-generated documents are normally not touched after issue."
                    ),
                )
            )
        elif delta < timedelta(0):
            findings.append(
                Finding(
                    code="modified_before_creation",
                    severity=Severity.HIGH,
                    title="Modification date is earlier than creation date",
                    detail="The timestamps are inconsistent, which indicates the metadata was tampered with.",
                )
            )
    for label, dt in (("creation", created), ("modification", modified)):
        if dt and dt > now + timedelta(days=1):
            findings.append(
                Finding(
                    code=f"future_{label}_date",
                    severity=Severity.HIGH,
                    title=f"The {label} date is in the future",
                    detail=f"The file claims a {label} time of {dt:%Y-%m-%d %H:%M} UTC, which has not happened yet.",
                )
            )
    return findings


def _humanize(delta: timedelta) -> str:
    seconds = int(delta.total_seconds())
    if seconds < 3600:
        return f"{seconds // 60} minutes"
    if seconds < 86400:
        return f"{seconds // 3600} hours"
    return f"{seconds // 86400} days"


# --- Content checks --------------------------------------------------------

_EMIRATES_ID = re.compile(r"\b784[- ]?(\d{4})[- ]?(\d{7})[- ]?(\d)\b")
_IBAN = re.compile(r"\b([A-Z]{2}\d{2}(?: ?[A-Z0-9]{4}){2,7}(?: ?[A-Z0-9]{1,3})?)\b")
_TEXT_DATE = re.compile(r"\b(\d{1,2})[/\-.](\d{1,2})[/\-.](\d{4})\b")


def _luhn_ok(digits: str) -> bool:
    total = 0
    for i, ch in enumerate(reversed(digits)):
        n = int(ch)
        if i % 2 == 1:
            n *= 2
            if n > 9:
                n -= 9
        total += n
    return total % 10 == 0


def _iban_ok(iban: str) -> bool:
    rearranged = iban[4:] + iban[:4]
    numeric = "".join(str(int(c, 36)) for c in rearranged)
    return int(numeric) % 97 == 1


def check_text_content(text: str, *, now: datetime | None = None) -> list[Finding]:
    findings: list[Finding] = []
    if not text:
        return findings
    now = now or datetime.now(UTC)

    for m in _EMIRATES_ID.finditer(text):
        digits = "784" + m.group(1) + m.group(2) + m.group(3)
        year = int(m.group(1))
        if not _luhn_ok(digits) or year < 1900 or year > now.year:
            findings.append(
                Finding(
                    code="invalid_emirates_id",
                    severity=Severity.CRITICAL,
                    title="Emirates ID number fails validation",
                    detail=(
                        f"The ID number {m.group(0)} does not pass the official checksum. "
                        "Real Emirates ID numbers always validate."
                    ),
                )
            )

    for m in _IBAN.finditer(text.upper()):
        iban = m.group(1).replace(" ", "")
        if len(iban) < 15 or not iban.startswith(("AE", "SA", "QA", "BH", "KW", "OM", "GB", "DE", "FR")):
            continue
        if iban.startswith("AE") and len(iban) != 23:
            findings.append(
                Finding(
                    code="invalid_iban_length",
                    severity=Severity.HIGH,
                    title="IBAN has the wrong length",
                    detail=f"UAE IBANs are 23 characters; '{iban}' has {len(iban)}.",
                )
            )
            continue
        if not _iban_ok(iban):
            findings.append(
                Finding(
                    code="invalid_iban",
                    severity=Severity.HIGH,
                    title="IBAN fails checksum",
                    detail=f"The account number '{iban}' is not a valid IBAN. Genuine bank receipts never contain an invalid IBAN.",
                )
            )

    for m in _TEXT_DATE.finditer(text):
        d, mo, y = int(m.group(1)), int(m.group(2)), int(m.group(3))
        if mo > 12 and d <= 12:
            d, mo = mo, d
        try:
            dt = datetime(y, mo, d, tzinfo=UTC)
        except ValueError:
            continue
        if dt > now + timedelta(days=1):
            findings.append(
                Finding(
                    code="future_date_in_text",
                    severity=Severity.MEDIUM,
                    title="Document text contains a future date",
                    detail=f"The document mentions {m.group(0)}, which is after today.",
                )
            )
            break

    return findings
